language: python

python:
    - 3.9

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  region: "us-west-2"
  app: "django-tutorial"
  env: "django_env"
  bucket_name: "elasticbeanstalk-us-west-2-508829990173"
  on:
      branch: main




